### ISSUE TITLE
Import Error: No module named 'flask'

### ISSUE THREAD

**Issue by mdrights** [shnode/Deerlet#4]
按照README.md写的步骤安装相应应用/依赖后，在执行

> sudo python3 main.py 
> 出现：
> Traceback (most recent call last):
>   File "main.py", line 6, in <module>
>     from flask import Flask
> ImportError: No module named 'flask'

求解答。
本机：Ubuntu 14.04

**Comment by shinux** [comment]
在 v2ex 中回答过您了，是执行命令所处的环境缺少 flask 依赖。

**Comment by shnode** [comment]
Hi, 不知道您解决这个问题了没有？

**Comment by blade254353074** [comment]
@mdrights 帮忙at
